on: 
  push:
    branches:
      - sharkbait
    tags-ignore:
      - 'v*.*'

name: Compiling

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run:  source $(pwd)/.github/build.sh
     