on: 
  push:
    tags:
      - 'v*.*'

name: Release

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: compile
      run:  source .github/build.sh
    - name: deploy  
      uses: actions/upload-artifact@v2
      with:
       path: "chute/AnyKernel/sharkbait*.zip"